<a href="https://colab.research.google.com/github/GoundlaNandini/TNSIF-BATCH-2-GOOGLE-COLAB-FILES/blob/main/Copy_of_Day_8_Batch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

Agenda:
1. What is NumPy?
2. Why Use NumPy?
3. Numpy Operations




**What is Numpy?**

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



**Why Use NumPy**

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
#Demo on list vs numpy interms of space
# Import sys module to measure memory usage
import sys

# Import NumPy library
import numpy as np

# Create a Python list containing 1 million integers
lst = list(range(1000000))

# Create a NumPy array containing 1 million integers
arr = np.arange(1000000)

# Get memory occupied by the list object
# Note: This does not include memory used by individual integer objects
print("List Size:", sys.getsizeof(lst), "bytes")

# Get actual memory occupied by NumPy array data
print("NumPy Array Size:", arr.nbytes, "bytes")


List Size: 8000056 bytes
NumPy Array Size: 8000000 bytes


In [ ]:
#Demo to check speed in List
# Import time module to measure execution time
import time

# Create a list with 1 million numbers
lst = list(range(1000000))

# Record start time
start = time.time()

# Add 10 to every element using list comprehension
result = [x + 10 for x in lst]

# Record end time
end = time.time()

# Calculate execution time
print("List Time:", end - start, "seconds")

List Time: 0.031786203384399414 seconds


In [ ]:
#Demo to check speed in Numpy
# Import NumPy and time modules
import numpy as np
import time

# Create NumPy array with 1 million numbers
arr = np.arange(1000000)

# Record start time
start = time.time()

# Vectorized operation
# NumPy internally performs this in optimized C code
result = arr + 10

# Record end time
end = time.time()

# Calculate execution time
print("NumPy Time:", end - start, "seconds")


NumPy Time: 0.011443376541137695 seconds


**Why is NumPy faster than Python Lists?**

1. NumPy stores data in contiguous memory locations.

2. All elements have the same data type.

3. Operations are implemented in optimized C code.

4. NumPy uses vectorization, avoiding Python loops.

5. Better CPU cache utilization.

**Why does NumPy use less memory?**

1. Python lists store references to objects.

2. Each integer in a list is a separate Python object.

3. NumPy stores raw values directly in memory.

4. Fixed data types reduce overhead.

**Array Operations**
1. Creating array
 NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

2. 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

3. 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

4. 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [ ]:
#Demo for types of array
import numpy as np

arr=np.array([10,20,30,40]) #1D
print(arr)

ar=np.array([[10,20,30],
     [40,50,60]])
print(ar)



[10 20 30 40]
[[10 20 30]
 [40 50 60]]


Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
#Demo for ndim
import numpy as np
ar=np.array([[1,2,3,4],[3,4,5,6]])
print(ar.ndim)

2


**NumPy Array Indexing**

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
#Demo for Indexing
import numpy as np
ar=np.array([1,2,3,4])
print(ar[2])

3


*Reshape*

Changes the shape (dimensions) of an array without changing its data.

Syntax: array.reshape(rows, columns)

In [ ]:
#Demo for Reshape
import numpy as np
ar=np.array([1,2,3,4,3,4])
print(ar.reshape(2,3))

[[1 2 3]
 [4 3 4]]


**Slicing**

Extracting a portion of an array.

Syntax: array[start:end]

In [ ]:
#Demo Slicing
import numpy as np
ar=np.array([1,2,3,4,3,4,5,6])
print(ar[1:6])

[2 3 4 3 4]


**Filtering**

Selects elements that satisfy a condition.

Syntax:
array[condition] --> a(a>25) --> a is array

In [ ]:
#Demo for filtering
import numpy as np
ar=np.array([1,2,30,49,39,89,5,6])
print(ar[ar>25])

[30 49 39 89]


**Creating a Range of Values**:

np.arange() generates a NumPy array containing evenly spaced values from start to stop (excluding stop) with the specified step size.

Syntax: np.arange(start, stop, step)

In [ ]:
#Demo for arange


**Array of Zeros**

Creates an array filled with zeros.

Syntax: np.zeros(shape)



In [ ]:
#Demo for zero's, one shape

Practice Questions:

1. Create a NumPy array containing numbers from 1 to 20 using arange().

2. Create an array of all zeros with 10 elements.

3. Create an array of all ones with 8 elements.

4. Create an array containing even numbers from 2 to 20.

5. Create an array and Find:Number of dimensions, Shape, Size, Data type

6. Multiply every element by 2.

7. Find the square of every element.

8. Divide every element by 10.

9. Create 1D array and Find: Sum, Mean, Maximum, Minimum

10. Create 2 arrays and Concatenate both arrays.

In [ ]:
# Import NumPy library
import numpy as np

# --------------------------------------------------
# 1. Create a NumPy array containing numbers from 1 to 20 using arange()
# --------------------------------------------------
arr1 = np.arange(1, 21)
print("Array from 1 to 20:")
print(arr1)

# --------------------------------------------------
# 2. Create an array of all zeros with 10 elements
# --------------------------------------------------
zeros_array = np.zeros(10)
print("\nArray of zeros:")
print(zeros_array)

# --------------------------------------------------
# 3. Create an array of all ones with 8 elements
# --------------------------------------------------
ones_array = np.ones(8)
print("\nArray of ones:")
print(ones_array)

# --------------------------------------------------
# 4. Create an array containing even numbers from 2 to 20
# --------------------------------------------------
even_array = np.arange(2, 21, 2)
print("\nEven numbers from 2 to 20:")
print(even_array)

# --------------------------------------------------
# 5. Create an array and find:
#    - Number of dimensions
#    - Shape
#    - Size
#    - Data type
# --------------------------------------------------
arr_info = np.array([[1, 2, 3],
                     [4, 5, 6]])

print("\nArray for information:")
print(arr_info)

print("Number of dimensions:", arr_info.ndim)
print("Shape:", arr_info.shape)
print("Size:", arr_info.size)
print("Data type:", arr_info.dtype)

# --------------------------------------------------
# 6. Multiply every element by 2
# --------------------------------------------------
multiply_by_2 = arr1 * 2
print("\nArray after multiplying by 2:")
print(multiply_by_2)

# --------------------------------------------------
# 7. Find the square of every element
# --------------------------------------------------
square_array = arr1 ** 2
print("\nSquare of each element:")
print(square_array)

# --------------------------------------------------
# 8. Divide every element by 10
# --------------------------------------------------
divide_by_10 = arr1 / 10
print("\nArray after dividing by 10:")
print(divide_by_10)

# --------------------------------------------------
# 9. Create a 1D array and find:
#    - Sum
#    - Mean
#    - Maximum
#    - Minimum
# --------------------------------------------------
one_d_array = np.array([10, 20, 30, 40, 50])

print("\n1D Array:")
print(one_d_array)

print("Sum:", np.sum(one_d_array))
print("Mean:", np.mean(one_d_array))
print("Maximum:", np.max(one_d_array))
print("Minimum:", np.min(one_d_array))

# --------------------------------------------------
# 10. Create 2 arrays and concatenate both arrays
# --------------------------------------------------
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([6, 7, 8, 9, 10])

concatenated_array = np.concatenate((array_a, array_b))

print("\nFirst Array:")
print(array_a)

print("Second Array:")
print(array_b)

print("Concatenated Array:")
print(concatenated_array)

Array from 1 to 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Array of zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of ones:
[1. 1. 1. 1. 1. 1. 1. 1.]

Even numbers from 2 to 20:
[ 2  4  6  8 10 12 14 16 18 20]

Array for information:
[[1 2 3]
 [4 5 6]]
Number of dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64

Array after multiplying by 2:
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]

Square of each element:
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]

Array after dividing by 10:
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2. ]

1D Array:
[10 20 30 40 50]
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10

First Array:
[1 2 3 4 5]
Second Array:
[ 6  7  8  9 10]
Concatenated Array:
[ 1  2  3  4  5  6  7  8  9 10]
